#CONNECTION_TYPE = "POLLING" 
CONNECTION_TYPE = "WEBHOOKS" 

NUM_STEPS = 100
AFFECT_DEFAULT = 5
AFFECT_MAX = 10

MAX_IMG_SIDE_SIZE_FOR_GAN_ST_TR = 500
MAX_IMG_SIDE_SIZE_FOR_SIMPLE_ST_TR = 300

DEFAULT_LANGUAGE = "ENG"
